name = "nexus-dashboard"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "SESSIONS"
id = "1395f0ca5e4a42e1814225084832e39a"

[vars]
DISCORD_CLIENT_ID = "1484039251954765985"
DASHBOARD_URL = "https://dashboard.nexus.ocxeru.com"